using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("Rhino.PersistentHashTable.Tests for Microsoft .NET Framework 3.5")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyCompanyAttribute("Rhino Tools Project")]
[assembly: AssemblyProductAttribute("Rhino.PersistentHashTable.Tests")]
[assembly: AssemblyCopyrightAttribute("Rhino Tools Project, original author or authors")]
[assembly: AssemblyVersionAttribute("1.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0.0")]
[assembly: AssemblyDelaySignAttribute(false)]

